### ISSUE TITLE
Script Error Fantasy Grounds Classic new update

### ISSUE THREAD

**Issue by Monesterio** [Althea21/witcher_fg_ruleset#23]
Hi
Fantasy Grounds Classic has been updated and now we get an script error each time a character is open... the current version is not working... 
Will you update the Witcher ruleset?

**Comment by Althea21** [comment]
Hello,
Thank you for reporting this issue.
I'll have a look asap, hopefully it's a quick fix but if not it may take some time as I don't have much free time these days. 
I'll let you know.

**Comment by Monesterio** [comment]
Hi, thanks a lot for your prompt reply.
It seems that it is not a quick fix... anyway, we will wait for your next update.

Let me recognize the great work you have done

**Comment by Althea21** [comment]
Hello 

I've just updated my FGC to have a look to your script error but I don't have any.
The only "problem" I see is the right toolbar has changed, there's no more the theme icons but ugly blue/gray text button (but they work fine).
Could try and see if you have a new FGC update available and if you still encounter any error send me a screenshot to help me find the source of the problem ?

Thanks,
~Althea

**Comment by Monesterio** [comment]
Hi,

Thanks a lot for your prompt answer.
The script error is just when you try to open the menu bar in characters
sheet to choose race, profession... etc

This is the screenshot:
[image: image.png]
[image: image.png]

Thanks again

**Comment by RHormiere** [comment]
Hello Althea, hope you're fine,

Thanks for your work on this package :)

I'm experiencing the same issue than Monesterio described. As per the error message, it seems to be linke to the combobox feature. I tried to debug it myself but could'nt achieve anything.

Here are the few arror messages I could gather, all thrown when clicking on, for example, the combobox designed to select the Race : 
`Ruleset Error: windowlist: Could not find windowclass (comboxbox_item) for control (race_cblist) in windowclass (charsheet_main)
Ruleset Warning: window: Anchored static height ignored for control () in windowclass (charsheet_main)
Ruleset Warning: window: Anchored static height ignored for control () in windowclass (charsheet_main)
[...]
Ruleset Warning: window: Anchored static height ignored for control () in windowclass (charsheet_main)
Ruleset Warning: window: Anchored static height ignored for control () in windowclass (charsheet_main)
Script Error: [string "common/scripts/combobox.lua"]:234: attempt to index upvalue '_ctrlList' (a nil value)
`
Another issue appears when clicking on the Skills tab : 
`
Script Error: [string "campaign/scripts/char_profession_details.lu..."]:69: attempt to index field '?' (a nil value)
`

If you need more info on these errors, feel free to ask me !

Regards,

**Comment by Althea21** [comment]
Thank you both for your precise reports and patience.
You can download a fixed version of the ruleset (hotfix 0.5.2) : https://github.com/Althea21/witcher_fg_ruleset/releases/

**Comment by RHormiere** [comment]
Hello,

Thanks for the quick reply and the update, the combobox bug is fixed :).
However, the "Skills tab issue" still remains. Here are some more details in case you need any:
 - The error only occurs one time, the first time the Skills tab is clicked
 - The following error message appears in the console (the same as before): `Script Error: [string "campaign/scripts/char_profession_details.lu..."]:69: attempt to index field '?' (a nil value)`
 - The Profession panel only contains its default values.

Regards,

**Comment by Monesterio** [comment]
Hi,

Althea, thanks a lot for your great effort and your support, you are
the best and you know it ;-)
I get the same error RHormiere told in the Skills tab, so it is not
important cause you can close the window and continue.

About the Profession panel, which values are not showing?

Again, thank you so much

**Comment by Monesterio** [comment]
Hi again,

I check it and I don't know why but the error is not fixed for me...
I'm sure I downloaded the last version 0.5.2 from the link provided but the
issue continues (Classic and Unity versions)

Thanks in advance

**Comment by Althea21** [comment]
Thank you both for your precise reports and patience.
You can download a fixed version of the ruleset (hotfix 0.5.2) : https://github.com/Althea21/witcher_fg_ruleset/releases/

**Comment by Althea21** [comment]
Hello there,

There's a new version available (0.5.3) that should fix the skills tab error : https://github.com/Althea21/witcher_fg_ruleset/releases/tag/0.5.3

Also there was an error in the download link from the previous version so you may have downloaded an older version but the link is correct now. To be sure you're running the last version (0.5.3) you can check the ruleset version in the chat right after loading a campaign.

Please let me know if all your bugs are fixed with this version

Thank you,
Althea

**Comment by Monesterio** [comment]
Oh my f... God... YOU ARE THE BEST (and you know it)
All is working perfectly now, I don't know if you have a Patreon or similar
but let me know if you have it.

>THANKS<

**Comment by Althea21** [comment]
Thank you very much for your kind words !
I'm glad all is back to normal. 
I don't have any patreon or similar, maybe I'll think of it one day, for now helping people to share games and stories with friends is 
enough ^^

**Comment by RHormiere** [comment]
Hi Althea,

All is working perfectly now, thanks for your awesome work :).

Also, I understand now the "issue" I was talking about related to the Profession panel. When a new character is created, no profession is set by default, and the profession panel is just filled with "Branch name" and "Skill name" labels.
No real issue then, I was just a little confused.

Thanks again for your work !

**Comment by Althea21** [comment]
There was still a problem with the profession skill initialization but it's solved now with this version.
Thank you for your feedback.
